// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkasdxqekatlmjhadikb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrYXNkeHFla2F0bG1qaGFkaWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjU1MTMsImV4cCI6MjA2NTk0MTUxM30.GFk9RjReZ5eIKikMB8pYWKN_1clwlLIwxiILGDq2D_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);