// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obywvfsoryacbewajlak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ieXd2ZnNvcnlhY2Jld2FqbGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTM1MTEsImV4cCI6MjA2NTkyOTUxMX0.ncWtpe4pb23S0blq6uUjyYz9zhxbQfCl-Gbi2V2is3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);